"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import artifact.artifact.v1alpha.file_pb2
import artifact.artifact.v1alpha.knowledge_base_pb2
import artifact.artifact.v1alpha.object_pb2
import artifact.artifact.v1alpha.system_pb2
import artifact.artifact.v1alpha.update_pb2
import collections.abc
import grpc
import grpc.aio
import typing

_T = typing.TypeVar('_T')

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta):
    ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore
    ...

class ArtifactPrivateServiceStub:
    """ArtifactPrivateService exposes the private endpoints that allow clients to
    manage artifacts.
    """

    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    CreateKnowledgeBaseAdmin: grpc.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.knowledge_base_pb2.CreateKnowledgeBaseAdminRequest,
        artifact.artifact.v1alpha.knowledge_base_pb2.CreateKnowledgeBaseAdminResponse,
    ]
    """Create a knowledge base without setting a creator (admin only)

    Creates a system-level knowledge base that has no creator. Used by internal
    services (e.g., agent-backend) to create shared knowledge bases like
    "instill-agent" that are not owned by any specific user.
    """
    GetObjectAdmin: grpc.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.object_pb2.GetObjectAdminRequest,
        artifact.artifact.v1alpha.object_pb2.GetObjectAdminResponse,
    ]
    """Get Object (admin only)"""
    UpdateObjectAdmin: grpc.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.object_pb2.UpdateObjectAdminRequest,
        artifact.artifact.v1alpha.object_pb2.UpdateObjectAdminResponse,
    ]
    """Update Object (admin only)"""
    DeleteFileAdmin: grpc.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.file_pb2.DeleteFileAdminRequest,
        artifact.artifact.v1alpha.file_pb2.DeleteFileAdminResponse,
    ]
    """GetFileAsMarkdownAdmin and GetChatFileAdmin have been removed.
    Use GetFile with VIEW_CONTENT instead to get the converted markdown via pre-signed URL.

    Delete a knowledge base file (admin only)

    Deletes a file from a knowledge base using only the file ID. Unlike the public
    DeleteFile endpoint which requires namespace and knowledge base IDs, this
    admin endpoint automatically looks up the file's knowledge base and owner to
    perform the deletion. Primarily used for integration testing and internal
    operations where the caller has a file ID but not the full resource path.
    Authentication metadata is injected automatically based on the file owner.
    """
    ExecuteKnowledgeBaseUpdateAdmin: grpc.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.update_pb2.ExecuteKnowledgeBaseUpdateAdminRequest,
        artifact.artifact.v1alpha.update_pb2.ExecuteKnowledgeBaseUpdateAdminResponse,
    ]
    """Knowledge Base Management Admin APIs

    Execute knowledge base update (admin only)
    """
    AbortKnowledgeBaseUpdateAdmin: grpc.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.update_pb2.AbortKnowledgeBaseUpdateAdminRequest,
        artifact.artifact.v1alpha.update_pb2.AbortKnowledgeBaseUpdateAdminResponse,
    ]
    """Abort knowledge base update (admin only)

    Cancels ongoing update workflows and cleans up staging KB resources
    (both finished and unfinished). Can abort specific knowledge bases by ID or
    all currently updating knowledge bases if no IDs provided. Sets knowledge base status
    to 'aborted'.
    """
    RollbackAdmin: grpc.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.update_pb2.RollbackAdminRequest,
        artifact.artifact.v1alpha.update_pb2.RollbackAdminResponse,
    ]
    """Rollback a specific knowledge base to previous version (admin only)"""
    PurgeRollbackAdmin: grpc.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.update_pb2.PurgeRollbackAdminRequest,
        artifact.artifact.v1alpha.update_pb2.PurgeRollbackAdminResponse,
    ]
    """Purge rollback immediately (admin only)"""
    SetRollbackRetentionAdmin: grpc.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.update_pb2.SetRollbackRetentionAdminRequest,
        artifact.artifact.v1alpha.update_pb2.SetRollbackRetentionAdminResponse,
    ]
    """Set rollback retention period (admin only)"""
    GetKnowledgeBaseUpdateStatusAdmin: grpc.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.update_pb2.GetKnowledgeBaseUpdateStatusAdminRequest,
        artifact.artifact.v1alpha.update_pb2.GetKnowledgeBaseUpdateStatusAdminResponse,
    ]
    """Get knowledge base update status (admin only)"""
    CreateSystemAdmin: grpc.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.system_pb2.CreateSystemAdminRequest,
        artifact.artifact.v1alpha.system_pb2.CreateSystemAdminResponse,
    ]
    """System Management Admin APIs

    Create a new system configuration (admin only)
    """
    GetSystemAdmin: grpc.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.system_pb2.GetSystemAdminRequest,
        artifact.artifact.v1alpha.system_pb2.GetSystemAdminResponse,
    ]
    """Get a system configuration (admin only)"""
    UpdateSystemAdmin: grpc.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.system_pb2.UpdateSystemAdminRequest,
        artifact.artifact.v1alpha.system_pb2.UpdateSystemAdminResponse,
    ]
    """Update an existing system configuration (admin only)"""
    DeleteSystemAdmin: grpc.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.system_pb2.DeleteSystemAdminRequest,
        artifact.artifact.v1alpha.system_pb2.DeleteSystemAdminResponse,
    ]
    """Delete a system configuration (admin only)"""
    ListSystemsAdmin: grpc.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.system_pb2.ListSystemsAdminRequest,
        artifact.artifact.v1alpha.system_pb2.ListSystemsAdminResponse,
    ]
    """List all system configurations (admin only)"""
    RenameSystemAdmin: grpc.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.system_pb2.RenameSystemAdminRequest,
        artifact.artifact.v1alpha.system_pb2.RenameSystemAdminResponse,
    ]
    """Rename a system configuration (admin only)"""
    SetDefaultSystemAdmin: grpc.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.system_pb2.SetDefaultSystemAdminRequest,
        artifact.artifact.v1alpha.system_pb2.SetDefaultSystemAdminResponse,
    ]
    """Set the default system configuration (admin only)"""
    GetDefaultSystemAdmin: grpc.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.system_pb2.GetDefaultSystemAdminRequest,
        artifact.artifact.v1alpha.system_pb2.GetDefaultSystemAdminResponse,
    ]
    """Get the current default system configuration (admin only)"""

class ArtifactPrivateServiceAsyncStub:
    """ArtifactPrivateService exposes the private endpoints that allow clients to
    manage artifacts.
    """

    CreateKnowledgeBaseAdmin: grpc.aio.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.knowledge_base_pb2.CreateKnowledgeBaseAdminRequest,
        artifact.artifact.v1alpha.knowledge_base_pb2.CreateKnowledgeBaseAdminResponse,
    ]
    """Create a knowledge base without setting a creator (admin only)

    Creates a system-level knowledge base that has no creator. Used by internal
    services (e.g., agent-backend) to create shared knowledge bases like
    "instill-agent" that are not owned by any specific user.
    """
    GetObjectAdmin: grpc.aio.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.object_pb2.GetObjectAdminRequest,
        artifact.artifact.v1alpha.object_pb2.GetObjectAdminResponse,
    ]
    """Get Object (admin only)"""
    UpdateObjectAdmin: grpc.aio.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.object_pb2.UpdateObjectAdminRequest,
        artifact.artifact.v1alpha.object_pb2.UpdateObjectAdminResponse,
    ]
    """Update Object (admin only)"""
    DeleteFileAdmin: grpc.aio.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.file_pb2.DeleteFileAdminRequest,
        artifact.artifact.v1alpha.file_pb2.DeleteFileAdminResponse,
    ]
    """GetFileAsMarkdownAdmin and GetChatFileAdmin have been removed.
    Use GetFile with VIEW_CONTENT instead to get the converted markdown via pre-signed URL.

    Delete a knowledge base file (admin only)

    Deletes a file from a knowledge base using only the file ID. Unlike the public
    DeleteFile endpoint which requires namespace and knowledge base IDs, this
    admin endpoint automatically looks up the file's knowledge base and owner to
    perform the deletion. Primarily used for integration testing and internal
    operations where the caller has a file ID but not the full resource path.
    Authentication metadata is injected automatically based on the file owner.
    """
    ExecuteKnowledgeBaseUpdateAdmin: grpc.aio.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.update_pb2.ExecuteKnowledgeBaseUpdateAdminRequest,
        artifact.artifact.v1alpha.update_pb2.ExecuteKnowledgeBaseUpdateAdminResponse,
    ]
    """Knowledge Base Management Admin APIs

    Execute knowledge base update (admin only)
    """
    AbortKnowledgeBaseUpdateAdmin: grpc.aio.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.update_pb2.AbortKnowledgeBaseUpdateAdminRequest,
        artifact.artifact.v1alpha.update_pb2.AbortKnowledgeBaseUpdateAdminResponse,
    ]
    """Abort knowledge base update (admin only)

    Cancels ongoing update workflows and cleans up staging KB resources
    (both finished and unfinished). Can abort specific knowledge bases by ID or
    all currently updating knowledge bases if no IDs provided. Sets knowledge base status
    to 'aborted'.
    """
    RollbackAdmin: grpc.aio.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.update_pb2.RollbackAdminRequest,
        artifact.artifact.v1alpha.update_pb2.RollbackAdminResponse,
    ]
    """Rollback a specific knowledge base to previous version (admin only)"""
    PurgeRollbackAdmin: grpc.aio.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.update_pb2.PurgeRollbackAdminRequest,
        artifact.artifact.v1alpha.update_pb2.PurgeRollbackAdminResponse,
    ]
    """Purge rollback immediately (admin only)"""
    SetRollbackRetentionAdmin: grpc.aio.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.update_pb2.SetRollbackRetentionAdminRequest,
        artifact.artifact.v1alpha.update_pb2.SetRollbackRetentionAdminResponse,
    ]
    """Set rollback retention period (admin only)"""
    GetKnowledgeBaseUpdateStatusAdmin: grpc.aio.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.update_pb2.GetKnowledgeBaseUpdateStatusAdminRequest,
        artifact.artifact.v1alpha.update_pb2.GetKnowledgeBaseUpdateStatusAdminResponse,
    ]
    """Get knowledge base update status (admin only)"""
    CreateSystemAdmin: grpc.aio.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.system_pb2.CreateSystemAdminRequest,
        artifact.artifact.v1alpha.system_pb2.CreateSystemAdminResponse,
    ]
    """System Management Admin APIs

    Create a new system configuration (admin only)
    """
    GetSystemAdmin: grpc.aio.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.system_pb2.GetSystemAdminRequest,
        artifact.artifact.v1alpha.system_pb2.GetSystemAdminResponse,
    ]
    """Get a system configuration (admin only)"""
    UpdateSystemAdmin: grpc.aio.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.system_pb2.UpdateSystemAdminRequest,
        artifact.artifact.v1alpha.system_pb2.UpdateSystemAdminResponse,
    ]
    """Update an existing system configuration (admin only)"""
    DeleteSystemAdmin: grpc.aio.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.system_pb2.DeleteSystemAdminRequest,
        artifact.artifact.v1alpha.system_pb2.DeleteSystemAdminResponse,
    ]
    """Delete a system configuration (admin only)"""
    ListSystemsAdmin: grpc.aio.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.system_pb2.ListSystemsAdminRequest,
        artifact.artifact.v1alpha.system_pb2.ListSystemsAdminResponse,
    ]
    """List all system configurations (admin only)"""
    RenameSystemAdmin: grpc.aio.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.system_pb2.RenameSystemAdminRequest,
        artifact.artifact.v1alpha.system_pb2.RenameSystemAdminResponse,
    ]
    """Rename a system configuration (admin only)"""
    SetDefaultSystemAdmin: grpc.aio.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.system_pb2.SetDefaultSystemAdminRequest,
        artifact.artifact.v1alpha.system_pb2.SetDefaultSystemAdminResponse,
    ]
    """Set the default system configuration (admin only)"""
    GetDefaultSystemAdmin: grpc.aio.UnaryUnaryMultiCallable[
        artifact.artifact.v1alpha.system_pb2.GetDefaultSystemAdminRequest,
        artifact.artifact.v1alpha.system_pb2.GetDefaultSystemAdminResponse,
    ]
    """Get the current default system configuration (admin only)"""

class ArtifactPrivateServiceServicer(metaclass=abc.ABCMeta):
    """ArtifactPrivateService exposes the private endpoints that allow clients to
    manage artifacts.
    """

    @abc.abstractmethod
    def CreateKnowledgeBaseAdmin(
        self,
        request: artifact.artifact.v1alpha.knowledge_base_pb2.CreateKnowledgeBaseAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[artifact.artifact.v1alpha.knowledge_base_pb2.CreateKnowledgeBaseAdminResponse, collections.abc.Awaitable[artifact.artifact.v1alpha.knowledge_base_pb2.CreateKnowledgeBaseAdminResponse]]:
        """Create a knowledge base without setting a creator (admin only)

        Creates a system-level knowledge base that has no creator. Used by internal
        services (e.g., agent-backend) to create shared knowledge bases like
        "instill-agent" that are not owned by any specific user.
        """
    @abc.abstractmethod
    def GetObjectAdmin(
        self,
        request: artifact.artifact.v1alpha.object_pb2.GetObjectAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[artifact.artifact.v1alpha.object_pb2.GetObjectAdminResponse, collections.abc.Awaitable[artifact.artifact.v1alpha.object_pb2.GetObjectAdminResponse]]:
        """Get Object (admin only)"""
    @abc.abstractmethod
    def UpdateObjectAdmin(
        self,
        request: artifact.artifact.v1alpha.object_pb2.UpdateObjectAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[artifact.artifact.v1alpha.object_pb2.UpdateObjectAdminResponse, collections.abc.Awaitable[artifact.artifact.v1alpha.object_pb2.UpdateObjectAdminResponse]]:
        """Update Object (admin only)"""
    @abc.abstractmethod
    def DeleteFileAdmin(
        self,
        request: artifact.artifact.v1alpha.file_pb2.DeleteFileAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[artifact.artifact.v1alpha.file_pb2.DeleteFileAdminResponse, collections.abc.Awaitable[artifact.artifact.v1alpha.file_pb2.DeleteFileAdminResponse]]:
        """GetFileAsMarkdownAdmin and GetChatFileAdmin have been removed.
        Use GetFile with VIEW_CONTENT instead to get the converted markdown via pre-signed URL.

        Delete a knowledge base file (admin only)

        Deletes a file from a knowledge base using only the file ID. Unlike the public
        DeleteFile endpoint which requires namespace and knowledge base IDs, this
        admin endpoint automatically looks up the file's knowledge base and owner to
        perform the deletion. Primarily used for integration testing and internal
        operations where the caller has a file ID but not the full resource path.
        Authentication metadata is injected automatically based on the file owner.
        """
    @abc.abstractmethod
    def ExecuteKnowledgeBaseUpdateAdmin(
        self,
        request: artifact.artifact.v1alpha.update_pb2.ExecuteKnowledgeBaseUpdateAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[artifact.artifact.v1alpha.update_pb2.ExecuteKnowledgeBaseUpdateAdminResponse, collections.abc.Awaitable[artifact.artifact.v1alpha.update_pb2.ExecuteKnowledgeBaseUpdateAdminResponse]]:
        """Knowledge Base Management Admin APIs

        Execute knowledge base update (admin only)
        """
    @abc.abstractmethod
    def AbortKnowledgeBaseUpdateAdmin(
        self,
        request: artifact.artifact.v1alpha.update_pb2.AbortKnowledgeBaseUpdateAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[artifact.artifact.v1alpha.update_pb2.AbortKnowledgeBaseUpdateAdminResponse, collections.abc.Awaitable[artifact.artifact.v1alpha.update_pb2.AbortKnowledgeBaseUpdateAdminResponse]]:
        """Abort knowledge base update (admin only)

        Cancels ongoing update workflows and cleans up staging KB resources
        (both finished and unfinished). Can abort specific knowledge bases by ID or
        all currently updating knowledge bases if no IDs provided. Sets knowledge base status
        to 'aborted'.
        """
    @abc.abstractmethod
    def RollbackAdmin(
        self,
        request: artifact.artifact.v1alpha.update_pb2.RollbackAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[artifact.artifact.v1alpha.update_pb2.RollbackAdminResponse, collections.abc.Awaitable[artifact.artifact.v1alpha.update_pb2.RollbackAdminResponse]]:
        """Rollback a specific knowledge base to previous version (admin only)"""
    @abc.abstractmethod
    def PurgeRollbackAdmin(
        self,
        request: artifact.artifact.v1alpha.update_pb2.PurgeRollbackAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[artifact.artifact.v1alpha.update_pb2.PurgeRollbackAdminResponse, collections.abc.Awaitable[artifact.artifact.v1alpha.update_pb2.PurgeRollbackAdminResponse]]:
        """Purge rollback immediately (admin only)"""
    @abc.abstractmethod
    def SetRollbackRetentionAdmin(
        self,
        request: artifact.artifact.v1alpha.update_pb2.SetRollbackRetentionAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[artifact.artifact.v1alpha.update_pb2.SetRollbackRetentionAdminResponse, collections.abc.Awaitable[artifact.artifact.v1alpha.update_pb2.SetRollbackRetentionAdminResponse]]:
        """Set rollback retention period (admin only)"""
    @abc.abstractmethod
    def GetKnowledgeBaseUpdateStatusAdmin(
        self,
        request: artifact.artifact.v1alpha.update_pb2.GetKnowledgeBaseUpdateStatusAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[artifact.artifact.v1alpha.update_pb2.GetKnowledgeBaseUpdateStatusAdminResponse, collections.abc.Awaitable[artifact.artifact.v1alpha.update_pb2.GetKnowledgeBaseUpdateStatusAdminResponse]]:
        """Get knowledge base update status (admin only)"""
    @abc.abstractmethod
    def CreateSystemAdmin(
        self,
        request: artifact.artifact.v1alpha.system_pb2.CreateSystemAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[artifact.artifact.v1alpha.system_pb2.CreateSystemAdminResponse, collections.abc.Awaitable[artifact.artifact.v1alpha.system_pb2.CreateSystemAdminResponse]]:
        """System Management Admin APIs

        Create a new system configuration (admin only)
        """
    @abc.abstractmethod
    def GetSystemAdmin(
        self,
        request: artifact.artifact.v1alpha.system_pb2.GetSystemAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[artifact.artifact.v1alpha.system_pb2.GetSystemAdminResponse, collections.abc.Awaitable[artifact.artifact.v1alpha.system_pb2.GetSystemAdminResponse]]:
        """Get a system configuration (admin only)"""
    @abc.abstractmethod
    def UpdateSystemAdmin(
        self,
        request: artifact.artifact.v1alpha.system_pb2.UpdateSystemAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[artifact.artifact.v1alpha.system_pb2.UpdateSystemAdminResponse, collections.abc.Awaitable[artifact.artifact.v1alpha.system_pb2.UpdateSystemAdminResponse]]:
        """Update an existing system configuration (admin only)"""
    @abc.abstractmethod
    def DeleteSystemAdmin(
        self,
        request: artifact.artifact.v1alpha.system_pb2.DeleteSystemAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[artifact.artifact.v1alpha.system_pb2.DeleteSystemAdminResponse, collections.abc.Awaitable[artifact.artifact.v1alpha.system_pb2.DeleteSystemAdminResponse]]:
        """Delete a system configuration (admin only)"""
    @abc.abstractmethod
    def ListSystemsAdmin(
        self,
        request: artifact.artifact.v1alpha.system_pb2.ListSystemsAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[artifact.artifact.v1alpha.system_pb2.ListSystemsAdminResponse, collections.abc.Awaitable[artifact.artifact.v1alpha.system_pb2.ListSystemsAdminResponse]]:
        """List all system configurations (admin only)"""
    @abc.abstractmethod
    def RenameSystemAdmin(
        self,
        request: artifact.artifact.v1alpha.system_pb2.RenameSystemAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[artifact.artifact.v1alpha.system_pb2.RenameSystemAdminResponse, collections.abc.Awaitable[artifact.artifact.v1alpha.system_pb2.RenameSystemAdminResponse]]:
        """Rename a system configuration (admin only)"""
    @abc.abstractmethod
    def SetDefaultSystemAdmin(
        self,
        request: artifact.artifact.v1alpha.system_pb2.SetDefaultSystemAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[artifact.artifact.v1alpha.system_pb2.SetDefaultSystemAdminResponse, collections.abc.Awaitable[artifact.artifact.v1alpha.system_pb2.SetDefaultSystemAdminResponse]]:
        """Set the default system configuration (admin only)"""
    @abc.abstractmethod
    def GetDefaultSystemAdmin(
        self,
        request: artifact.artifact.v1alpha.system_pb2.GetDefaultSystemAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[artifact.artifact.v1alpha.system_pb2.GetDefaultSystemAdminResponse, collections.abc.Awaitable[artifact.artifact.v1alpha.system_pb2.GetDefaultSystemAdminResponse]]:
        """Get the current default system configuration (admin only)"""

def add_ArtifactPrivateServiceServicer_to_server(servicer: ArtifactPrivateServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
