# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from model.ray import serve_pb2 as model_dot_ray_dot_serve__pb2


class RayServeAPIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListApplications = channel.unary_unary(
                '/ray.serve.RayServeAPIService/ListApplications',
                request_serializer=model_dot_ray_dot_serve__pb2.ListApplicationsRequest.SerializeToString,
                response_deserializer=model_dot_ray_dot_serve__pb2.ListApplicationsResponse.FromString,
                )
        self.Healthz = channel.unary_unary(
                '/ray.serve.RayServeAPIService/Healthz',
                request_serializer=model_dot_ray_dot_serve__pb2.HealthzRequest.SerializeToString,
                response_deserializer=model_dot_ray_dot_serve__pb2.HealthzResponse.FromString,
                )


class RayServeAPIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListApplications(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Healthz(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RayServeAPIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListApplications': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApplications,
                    request_deserializer=model_dot_ray_dot_serve__pb2.ListApplicationsRequest.FromString,
                    response_serializer=model_dot_ray_dot_serve__pb2.ListApplicationsResponse.SerializeToString,
            ),
            'Healthz': grpc.unary_unary_rpc_method_handler(
                    servicer.Healthz,
                    request_deserializer=model_dot_ray_dot_serve__pb2.HealthzRequest.FromString,
                    response_serializer=model_dot_ray_dot_serve__pb2.HealthzResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ray.serve.RayServeAPIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RayServeAPIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListApplications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ray.serve.RayServeAPIService/ListApplications',
            model_dot_ray_dot_serve__pb2.ListApplicationsRequest.SerializeToString,
            model_dot_ray_dot_serve__pb2.ListApplicationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Healthz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ray.serve.RayServeAPIService/Healthz',
            model_dot_ray_dot_serve__pb2.HealthzRequest.SerializeToString,
            model_dot_ray_dot_serve__pb2.HealthzResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
