"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import collections.abc
import core.mgmt.v1beta.metric_pb2
import core.mgmt.v1beta.mgmt_pb2
import grpc
import grpc.aio
import typing

_T = typing.TypeVar('_T')

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta):
    ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore
    ...

class MgmtPublicServiceStub:
    """Mgmt service responds to external access"""

    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    Liveness: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.LivenessRequest,
        core.mgmt.v1beta.mgmt_pb2.LivenessResponse,
    ]
    """Liveness method receives a LivenessRequest message and returns a
    LivenessResponse message.
    See https://github.com/grpc/grpc/blob/master/doc/health-checking.md
    """
    Readiness: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.ReadinessRequest,
        core.mgmt.v1beta.mgmt_pb2.ReadinessResponse,
    ]
    """Readiness method receives a ReadinessRequest message and returns a
    ReadinessResponse message.
    See https://github.com/grpc/grpc/blob/master/doc/health-checking.md
    """
    CheckNamespace: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.CheckNamespaceRequest,
        core.mgmt.v1beta.mgmt_pb2.CheckNamespaceResponse,
    ]
    """Check namespace"""
    ListUsers: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.ListUsersRequest,
        core.mgmt.v1beta.mgmt_pb2.ListUsersResponse,
    ]
    """ListUsers method receives a ListUsersRequest message and returns a
    ListUsersResponse message.
    """
    GetUser: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.GetUserRequest,
        core.mgmt.v1beta.mgmt_pb2.GetUserResponse,
    ]
    """GetUser method receives a GetUser message and returns a
    GetUser message.
    """
    PatchAuthenticatedUser: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.PatchAuthenticatedUserRequest,
        core.mgmt.v1beta.mgmt_pb2.PatchAuthenticatedUserResponse,
    ]
    """PatchAuthenticatedUser method receives a PatchAuthenticatedUserRequest
    message and returns a PatchAuthenticatedUserResponse message.
    """
    ListUserMemberships: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.ListUserMembershipsRequest,
        core.mgmt.v1beta.mgmt_pb2.ListUserMembershipsResponse,
    ]
    """ListUserMemberships method receives a ListUserMembershipsRequest message and returns a
    ListUserMembershipsResponse message.
    """
    GetUserMembership: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.GetUserMembershipRequest,
        core.mgmt.v1beta.mgmt_pb2.GetUserMembershipResponse,
    ]
    """GetUserMembership method receives a GetUserMembershipRequest message and returns a
    GetUserMembershipResponse message.
    """
    UpdateUserMembership: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.UpdateUserMembershipRequest,
        core.mgmt.v1beta.mgmt_pb2.UpdateUserMembershipResponse,
    ]
    """UpdateUserMembership method receives a UpdateUserMembershipRequest message and returns
    a UpdateUserMembershipResponse message.
    """
    DeleteUserMembership: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.DeleteUserMembershipRequest,
        core.mgmt.v1beta.mgmt_pb2.DeleteUserMembershipResponse,
    ]
    """DeleteUserMembership method receives a DeleteUserMembershipRequest message and returns
    a DeleteUserMembershipResponse message.
    """
    ListOrganizations: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.ListOrganizationsRequest,
        core.mgmt.v1beta.mgmt_pb2.ListOrganizationsResponse,
    ]
    """ListOrganizations method receives a ListOrganizationsRequest message and returns
    a ListOrganizationsResponse message.
    """
    CreateOrganization: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.CreateOrganizationRequest,
        core.mgmt.v1beta.mgmt_pb2.CreateOrganizationResponse,
    ]
    """CreateOrganization receives a CreateOrganizationRequest message and returns a
    a GetOrganizationResponse
    """
    GetOrganization: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.GetOrganizationRequest,
        core.mgmt.v1beta.mgmt_pb2.GetOrganizationResponse,
    ]
    """GetOrganization method receives a GetOrganizationRequest message and returns
    a GetOrganizationResponse message.
    """
    UpdateOrganization: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.UpdateOrganizationRequest,
        core.mgmt.v1beta.mgmt_pb2.UpdateOrganizationResponse,
    ]
    """UpdateOrganization method receives a UpdateOrganizationRequest message and
    returns a UpdateOrganizationResponse
    """
    DeleteOrganization: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.DeleteOrganizationRequest,
        core.mgmt.v1beta.mgmt_pb2.DeleteOrganizationResponse,
    ]
    """DeleteOrganization method receives a DeleteOrganizationRequest message and
    returns a DeleteOrganizationResponse
    """
    ListOrganizationMemberships: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.ListOrganizationMembershipsRequest,
        core.mgmt.v1beta.mgmt_pb2.ListOrganizationMembershipsResponse,
    ]
    """ListOrganizationMemberships method receives a ListOrganizationMembershipsRequest message and returns a
    ListOrganizationMembershipsResponse message.
    """
    GetOrganizationMembership: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.GetOrganizationMembershipRequest,
        core.mgmt.v1beta.mgmt_pb2.GetOrganizationMembershipResponse,
    ]
    """GetOrganizationMembership method receives a GetOrganizationMembershipRequest message and returns a
    GetOrganizationMembershipResponse message.
    """
    UpdateOrganizationMembership: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.UpdateOrganizationMembershipRequest,
        core.mgmt.v1beta.mgmt_pb2.UpdateOrganizationMembershipResponse,
    ]
    """UpdateOrganizationMembership method receives a UpdateOrganizationMembershipRequest message and returns
    a UpdateOrganizationMembershipResponse message.
    """
    DeleteOrganizationMembership: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.DeleteOrganizationMembershipRequest,
        core.mgmt.v1beta.mgmt_pb2.DeleteOrganizationMembershipResponse,
    ]
    """DeleteOrganizationMembership method receives a DeleteOrganizationMembershipRequest message and returns
    a DeleteOrganizationMembershipResponse message.
    """
    GetUserSubscription: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.GetUserSubscriptionRequest,
        core.mgmt.v1beta.mgmt_pb2.GetUserSubscriptionResponse,
    ]
    """GetUserSubscription"""
    GetOrganizationSubscription: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.GetOrganizationSubscriptionRequest,
        core.mgmt.v1beta.mgmt_pb2.GetOrganizationSubscriptionResponse,
    ]
    """GetOrganizationSubscription"""
    CreateToken: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.CreateTokenRequest,
        core.mgmt.v1beta.mgmt_pb2.CreateTokenResponse,
    ]
    """CreateToken method receives a CreateTokenRequest message and returns
    a CreateTokenResponse message.
    """
    ListTokens: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.ListTokensRequest,
        core.mgmt.v1beta.mgmt_pb2.ListTokensResponse,
    ]
    """ListTokens method receives a ListTokensRequest message and returns a
    ListTokensResponse message.
    """
    GetToken: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.GetTokenRequest,
        core.mgmt.v1beta.mgmt_pb2.GetTokenResponse,
    ]
    """GetToken method receives a GetTokenRequest message and returns a
    GetTokenResponse message.
    """
    DeleteToken: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.DeleteTokenRequest,
        core.mgmt.v1beta.mgmt_pb2.DeleteTokenResponse,
    ]
    """DeleteToken method receives a DeleteTokenRequest message and returns
    a DeleteTokenResponse message.
    """
    ValidateToken: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.ValidateTokenRequest,
        core.mgmt.v1beta.mgmt_pb2.ValidateTokenResponse,
    ]
    """ValidateToken method receives a ValidateTokenRequest message and returns
    a ValidateTokenResponse message.
    """
    ListPipelineTriggerRecords: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.metric_pb2.ListPipelineTriggerRecordsRequest,
        core.mgmt.v1beta.metric_pb2.ListPipelineTriggerRecordsResponse,
    ]
    """========== Metric endpoints

    ListPipelineTriggerRecords method receives a
    ListPipelineTriggerRecordsRequest message and returns a
    ListPipelineTriggerRecordsResponse message.
    """
    ListPipelineTriggerTableRecords: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.metric_pb2.ListPipelineTriggerTableRecordsRequest,
        core.mgmt.v1beta.metric_pb2.ListPipelineTriggerTableRecordsResponse,
    ]
    """ListPipelineTriggerTableRecords method receives a
    ListPipelineTriggerTableRecordsRequest message and returns a
    ListPipelineTriggerTableRecordsResponse message.
    """
    ListPipelineTriggerChartRecords: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.metric_pb2.ListPipelineTriggerChartRecordsRequest,
        core.mgmt.v1beta.metric_pb2.ListPipelineTriggerChartRecordsResponse,
    ]
    """ListPipelineTriggerChartRecords method receives a
    ListPipelineTriggerChartRecordsRequest message and returns a
    ListPipelineTriggerChartRecordsResponse message.
    """
    ListConnectorExecuteRecords: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.metric_pb2.ListConnectorExecuteRecordsRequest,
        core.mgmt.v1beta.metric_pb2.ListConnectorExecuteRecordsResponse,
    ]
    """ListConnectorExecuteRecords method receives a
    ListConnectorExecuteRecordsRequest message and returns a
    ListConnectorExecuteRecordsResponse message.
    """
    ListConnectorExecuteTableRecords: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.metric_pb2.ListConnectorExecuteTableRecordsRequest,
        core.mgmt.v1beta.metric_pb2.ListConnectorExecuteTableRecordsResponse,
    ]
    """ListConnectorExecuteTableRecords method receives a
    ListConnectorExecuteTableRecordsRequest message and returns a
    ListConnectorExecuteTableRecordsResponse message.
    """
    ListConnectorExecuteChartRecords: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.metric_pb2.ListConnectorExecuteChartRecordsRequest,
        core.mgmt.v1beta.metric_pb2.ListConnectorExecuteChartRecordsResponse,
    ]
    """ListConnectorExecuteChartRecords method receives a
    ListConnectorExecuteChartRecordsRequest message and returns a
    ListConnectorExecuteChartRecordsResponse message.
    """
    AuthTokenIssuer: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.AuthTokenIssuerRequest,
        core.mgmt.v1beta.mgmt_pb2.AuthTokenIssuerResponse,
    ]
    """AuthTokenIssuer endpoint"""
    AuthLogin: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.AuthLoginRequest,
        core.mgmt.v1beta.mgmt_pb2.AuthLoginResponse,
    ]
    """Auth Login endpoint"""
    AuthLogout: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.AuthLogoutRequest,
        core.mgmt.v1beta.mgmt_pb2.AuthLogoutResponse,
    ]
    """Auth Logout endpoint"""
    AuthChangePassword: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.AuthChangePasswordRequest,
        core.mgmt.v1beta.mgmt_pb2.AuthChangePasswordResponse,
    ]
    """Auth Change password endpoint"""
    AuthValidateAccessToken: grpc.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.AuthValidateAccessTokenRequest,
        core.mgmt.v1beta.mgmt_pb2.AuthValidateAccessTokenResponse,
    ]
    """Auth AccessToken validation endpoint"""

class MgmtPublicServiceAsyncStub:
    """Mgmt service responds to external access"""

    Liveness: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.LivenessRequest,
        core.mgmt.v1beta.mgmt_pb2.LivenessResponse,
    ]
    """Liveness method receives a LivenessRequest message and returns a
    LivenessResponse message.
    See https://github.com/grpc/grpc/blob/master/doc/health-checking.md
    """
    Readiness: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.ReadinessRequest,
        core.mgmt.v1beta.mgmt_pb2.ReadinessResponse,
    ]
    """Readiness method receives a ReadinessRequest message and returns a
    ReadinessResponse message.
    See https://github.com/grpc/grpc/blob/master/doc/health-checking.md
    """
    CheckNamespace: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.CheckNamespaceRequest,
        core.mgmt.v1beta.mgmt_pb2.CheckNamespaceResponse,
    ]
    """Check namespace"""
    ListUsers: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.ListUsersRequest,
        core.mgmt.v1beta.mgmt_pb2.ListUsersResponse,
    ]
    """ListUsers method receives a ListUsersRequest message and returns a
    ListUsersResponse message.
    """
    GetUser: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.GetUserRequest,
        core.mgmt.v1beta.mgmt_pb2.GetUserResponse,
    ]
    """GetUser method receives a GetUser message and returns a
    GetUser message.
    """
    PatchAuthenticatedUser: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.PatchAuthenticatedUserRequest,
        core.mgmt.v1beta.mgmt_pb2.PatchAuthenticatedUserResponse,
    ]
    """PatchAuthenticatedUser method receives a PatchAuthenticatedUserRequest
    message and returns a PatchAuthenticatedUserResponse message.
    """
    ListUserMemberships: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.ListUserMembershipsRequest,
        core.mgmt.v1beta.mgmt_pb2.ListUserMembershipsResponse,
    ]
    """ListUserMemberships method receives a ListUserMembershipsRequest message and returns a
    ListUserMembershipsResponse message.
    """
    GetUserMembership: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.GetUserMembershipRequest,
        core.mgmt.v1beta.mgmt_pb2.GetUserMembershipResponse,
    ]
    """GetUserMembership method receives a GetUserMembershipRequest message and returns a
    GetUserMembershipResponse message.
    """
    UpdateUserMembership: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.UpdateUserMembershipRequest,
        core.mgmt.v1beta.mgmt_pb2.UpdateUserMembershipResponse,
    ]
    """UpdateUserMembership method receives a UpdateUserMembershipRequest message and returns
    a UpdateUserMembershipResponse message.
    """
    DeleteUserMembership: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.DeleteUserMembershipRequest,
        core.mgmt.v1beta.mgmt_pb2.DeleteUserMembershipResponse,
    ]
    """DeleteUserMembership method receives a DeleteUserMembershipRequest message and returns
    a DeleteUserMembershipResponse message.
    """
    ListOrganizations: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.ListOrganizationsRequest,
        core.mgmt.v1beta.mgmt_pb2.ListOrganizationsResponse,
    ]
    """ListOrganizations method receives a ListOrganizationsRequest message and returns
    a ListOrganizationsResponse message.
    """
    CreateOrganization: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.CreateOrganizationRequest,
        core.mgmt.v1beta.mgmt_pb2.CreateOrganizationResponse,
    ]
    """CreateOrganization receives a CreateOrganizationRequest message and returns a
    a GetOrganizationResponse
    """
    GetOrganization: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.GetOrganizationRequest,
        core.mgmt.v1beta.mgmt_pb2.GetOrganizationResponse,
    ]
    """GetOrganization method receives a GetOrganizationRequest message and returns
    a GetOrganizationResponse message.
    """
    UpdateOrganization: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.UpdateOrganizationRequest,
        core.mgmt.v1beta.mgmt_pb2.UpdateOrganizationResponse,
    ]
    """UpdateOrganization method receives a UpdateOrganizationRequest message and
    returns a UpdateOrganizationResponse
    """
    DeleteOrganization: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.DeleteOrganizationRequest,
        core.mgmt.v1beta.mgmt_pb2.DeleteOrganizationResponse,
    ]
    """DeleteOrganization method receives a DeleteOrganizationRequest message and
    returns a DeleteOrganizationResponse
    """
    ListOrganizationMemberships: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.ListOrganizationMembershipsRequest,
        core.mgmt.v1beta.mgmt_pb2.ListOrganizationMembershipsResponse,
    ]
    """ListOrganizationMemberships method receives a ListOrganizationMembershipsRequest message and returns a
    ListOrganizationMembershipsResponse message.
    """
    GetOrganizationMembership: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.GetOrganizationMembershipRequest,
        core.mgmt.v1beta.mgmt_pb2.GetOrganizationMembershipResponse,
    ]
    """GetOrganizationMembership method receives a GetOrganizationMembershipRequest message and returns a
    GetOrganizationMembershipResponse message.
    """
    UpdateOrganizationMembership: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.UpdateOrganizationMembershipRequest,
        core.mgmt.v1beta.mgmt_pb2.UpdateOrganizationMembershipResponse,
    ]
    """UpdateOrganizationMembership method receives a UpdateOrganizationMembershipRequest message and returns
    a UpdateOrganizationMembershipResponse message.
    """
    DeleteOrganizationMembership: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.DeleteOrganizationMembershipRequest,
        core.mgmt.v1beta.mgmt_pb2.DeleteOrganizationMembershipResponse,
    ]
    """DeleteOrganizationMembership method receives a DeleteOrganizationMembershipRequest message and returns
    a DeleteOrganizationMembershipResponse message.
    """
    GetUserSubscription: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.GetUserSubscriptionRequest,
        core.mgmt.v1beta.mgmt_pb2.GetUserSubscriptionResponse,
    ]
    """GetUserSubscription"""
    GetOrganizationSubscription: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.GetOrganizationSubscriptionRequest,
        core.mgmt.v1beta.mgmt_pb2.GetOrganizationSubscriptionResponse,
    ]
    """GetOrganizationSubscription"""
    CreateToken: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.CreateTokenRequest,
        core.mgmt.v1beta.mgmt_pb2.CreateTokenResponse,
    ]
    """CreateToken method receives a CreateTokenRequest message and returns
    a CreateTokenResponse message.
    """
    ListTokens: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.ListTokensRequest,
        core.mgmt.v1beta.mgmt_pb2.ListTokensResponse,
    ]
    """ListTokens method receives a ListTokensRequest message and returns a
    ListTokensResponse message.
    """
    GetToken: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.GetTokenRequest,
        core.mgmt.v1beta.mgmt_pb2.GetTokenResponse,
    ]
    """GetToken method receives a GetTokenRequest message and returns a
    GetTokenResponse message.
    """
    DeleteToken: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.DeleteTokenRequest,
        core.mgmt.v1beta.mgmt_pb2.DeleteTokenResponse,
    ]
    """DeleteToken method receives a DeleteTokenRequest message and returns
    a DeleteTokenResponse message.
    """
    ValidateToken: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.ValidateTokenRequest,
        core.mgmt.v1beta.mgmt_pb2.ValidateTokenResponse,
    ]
    """ValidateToken method receives a ValidateTokenRequest message and returns
    a ValidateTokenResponse message.
    """
    ListPipelineTriggerRecords: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.metric_pb2.ListPipelineTriggerRecordsRequest,
        core.mgmt.v1beta.metric_pb2.ListPipelineTriggerRecordsResponse,
    ]
    """========== Metric endpoints

    ListPipelineTriggerRecords method receives a
    ListPipelineTriggerRecordsRequest message and returns a
    ListPipelineTriggerRecordsResponse message.
    """
    ListPipelineTriggerTableRecords: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.metric_pb2.ListPipelineTriggerTableRecordsRequest,
        core.mgmt.v1beta.metric_pb2.ListPipelineTriggerTableRecordsResponse,
    ]
    """ListPipelineTriggerTableRecords method receives a
    ListPipelineTriggerTableRecordsRequest message and returns a
    ListPipelineTriggerTableRecordsResponse message.
    """
    ListPipelineTriggerChartRecords: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.metric_pb2.ListPipelineTriggerChartRecordsRequest,
        core.mgmt.v1beta.metric_pb2.ListPipelineTriggerChartRecordsResponse,
    ]
    """ListPipelineTriggerChartRecords method receives a
    ListPipelineTriggerChartRecordsRequest message and returns a
    ListPipelineTriggerChartRecordsResponse message.
    """
    ListConnectorExecuteRecords: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.metric_pb2.ListConnectorExecuteRecordsRequest,
        core.mgmt.v1beta.metric_pb2.ListConnectorExecuteRecordsResponse,
    ]
    """ListConnectorExecuteRecords method receives a
    ListConnectorExecuteRecordsRequest message and returns a
    ListConnectorExecuteRecordsResponse message.
    """
    ListConnectorExecuteTableRecords: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.metric_pb2.ListConnectorExecuteTableRecordsRequest,
        core.mgmt.v1beta.metric_pb2.ListConnectorExecuteTableRecordsResponse,
    ]
    """ListConnectorExecuteTableRecords method receives a
    ListConnectorExecuteTableRecordsRequest message and returns a
    ListConnectorExecuteTableRecordsResponse message.
    """
    ListConnectorExecuteChartRecords: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.metric_pb2.ListConnectorExecuteChartRecordsRequest,
        core.mgmt.v1beta.metric_pb2.ListConnectorExecuteChartRecordsResponse,
    ]
    """ListConnectorExecuteChartRecords method receives a
    ListConnectorExecuteChartRecordsRequest message and returns a
    ListConnectorExecuteChartRecordsResponse message.
    """
    AuthTokenIssuer: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.AuthTokenIssuerRequest,
        core.mgmt.v1beta.mgmt_pb2.AuthTokenIssuerResponse,
    ]
    """AuthTokenIssuer endpoint"""
    AuthLogin: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.AuthLoginRequest,
        core.mgmt.v1beta.mgmt_pb2.AuthLoginResponse,
    ]
    """Auth Login endpoint"""
    AuthLogout: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.AuthLogoutRequest,
        core.mgmt.v1beta.mgmt_pb2.AuthLogoutResponse,
    ]
    """Auth Logout endpoint"""
    AuthChangePassword: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.AuthChangePasswordRequest,
        core.mgmt.v1beta.mgmt_pb2.AuthChangePasswordResponse,
    ]
    """Auth Change password endpoint"""
    AuthValidateAccessToken: grpc.aio.UnaryUnaryMultiCallable[
        core.mgmt.v1beta.mgmt_pb2.AuthValidateAccessTokenRequest,
        core.mgmt.v1beta.mgmt_pb2.AuthValidateAccessTokenResponse,
    ]
    """Auth AccessToken validation endpoint"""

class MgmtPublicServiceServicer(metaclass=abc.ABCMeta):
    """Mgmt service responds to external access"""

    @abc.abstractmethod
    def Liveness(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.LivenessRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.LivenessResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.LivenessResponse]]:
        """Liveness method receives a LivenessRequest message and returns a
        LivenessResponse message.
        See https://github.com/grpc/grpc/blob/master/doc/health-checking.md
        """
    @abc.abstractmethod
    def Readiness(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.ReadinessRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.ReadinessResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.ReadinessResponse]]:
        """Readiness method receives a ReadinessRequest message and returns a
        ReadinessResponse message.
        See https://github.com/grpc/grpc/blob/master/doc/health-checking.md
        """
    @abc.abstractmethod
    def CheckNamespace(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.CheckNamespaceRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.CheckNamespaceResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.CheckNamespaceResponse]]:
        """Check namespace"""
    @abc.abstractmethod
    def ListUsers(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.ListUsersRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.ListUsersResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.ListUsersResponse]]:
        """ListUsers method receives a ListUsersRequest message and returns a
        ListUsersResponse message.
        """
    @abc.abstractmethod
    def GetUser(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.GetUserRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.GetUserResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.GetUserResponse]]:
        """GetUser method receives a GetUser message and returns a
        GetUser message.
        """
    @abc.abstractmethod
    def PatchAuthenticatedUser(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.PatchAuthenticatedUserRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.PatchAuthenticatedUserResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.PatchAuthenticatedUserResponse]]:
        """PatchAuthenticatedUser method receives a PatchAuthenticatedUserRequest
        message and returns a PatchAuthenticatedUserResponse message.
        """
    @abc.abstractmethod
    def ListUserMemberships(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.ListUserMembershipsRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.ListUserMembershipsResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.ListUserMembershipsResponse]]:
        """ListUserMemberships method receives a ListUserMembershipsRequest message and returns a
        ListUserMembershipsResponse message.
        """
    @abc.abstractmethod
    def GetUserMembership(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.GetUserMembershipRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.GetUserMembershipResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.GetUserMembershipResponse]]:
        """GetUserMembership method receives a GetUserMembershipRequest message and returns a
        GetUserMembershipResponse message.
        """
    @abc.abstractmethod
    def UpdateUserMembership(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.UpdateUserMembershipRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.UpdateUserMembershipResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.UpdateUserMembershipResponse]]:
        """UpdateUserMembership method receives a UpdateUserMembershipRequest message and returns
        a UpdateUserMembershipResponse message.
        """
    @abc.abstractmethod
    def DeleteUserMembership(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.DeleteUserMembershipRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.DeleteUserMembershipResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.DeleteUserMembershipResponse]]:
        """DeleteUserMembership method receives a DeleteUserMembershipRequest message and returns
        a DeleteUserMembershipResponse message.
        """
    @abc.abstractmethod
    def ListOrganizations(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.ListOrganizationsRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.ListOrganizationsResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.ListOrganizationsResponse]]:
        """ListOrganizations method receives a ListOrganizationsRequest message and returns
        a ListOrganizationsResponse message.
        """
    @abc.abstractmethod
    def CreateOrganization(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.CreateOrganizationRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.CreateOrganizationResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.CreateOrganizationResponse]]:
        """CreateOrganization receives a CreateOrganizationRequest message and returns a
        a GetOrganizationResponse
        """
    @abc.abstractmethod
    def GetOrganization(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.GetOrganizationRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.GetOrganizationResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.GetOrganizationResponse]]:
        """GetOrganization method receives a GetOrganizationRequest message and returns
        a GetOrganizationResponse message.
        """
    @abc.abstractmethod
    def UpdateOrganization(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.UpdateOrganizationRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.UpdateOrganizationResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.UpdateOrganizationResponse]]:
        """UpdateOrganization method receives a UpdateOrganizationRequest message and
        returns a UpdateOrganizationResponse
        """
    @abc.abstractmethod
    def DeleteOrganization(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.DeleteOrganizationRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.DeleteOrganizationResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.DeleteOrganizationResponse]]:
        """DeleteOrganization method receives a DeleteOrganizationRequest message and
        returns a DeleteOrganizationResponse
        """
    @abc.abstractmethod
    def ListOrganizationMemberships(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.ListOrganizationMembershipsRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.ListOrganizationMembershipsResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.ListOrganizationMembershipsResponse]]:
        """ListOrganizationMemberships method receives a ListOrganizationMembershipsRequest message and returns a
        ListOrganizationMembershipsResponse message.
        """
    @abc.abstractmethod
    def GetOrganizationMembership(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.GetOrganizationMembershipRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.GetOrganizationMembershipResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.GetOrganizationMembershipResponse]]:
        """GetOrganizationMembership method receives a GetOrganizationMembershipRequest message and returns a
        GetOrganizationMembershipResponse message.
        """
    @abc.abstractmethod
    def UpdateOrganizationMembership(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.UpdateOrganizationMembershipRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.UpdateOrganizationMembershipResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.UpdateOrganizationMembershipResponse]]:
        """UpdateOrganizationMembership method receives a UpdateOrganizationMembershipRequest message and returns
        a UpdateOrganizationMembershipResponse message.
        """
    @abc.abstractmethod
    def DeleteOrganizationMembership(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.DeleteOrganizationMembershipRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.DeleteOrganizationMembershipResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.DeleteOrganizationMembershipResponse]]:
        """DeleteOrganizationMembership method receives a DeleteOrganizationMembershipRequest message and returns
        a DeleteOrganizationMembershipResponse message.
        """
    @abc.abstractmethod
    def GetUserSubscription(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.GetUserSubscriptionRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.GetUserSubscriptionResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.GetUserSubscriptionResponse]]:
        """GetUserSubscription"""
    @abc.abstractmethod
    def GetOrganizationSubscription(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.GetOrganizationSubscriptionRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.GetOrganizationSubscriptionResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.GetOrganizationSubscriptionResponse]]:
        """GetOrganizationSubscription"""
    @abc.abstractmethod
    def CreateToken(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.CreateTokenRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.CreateTokenResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.CreateTokenResponse]]:
        """CreateToken method receives a CreateTokenRequest message and returns
        a CreateTokenResponse message.
        """
    @abc.abstractmethod
    def ListTokens(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.ListTokensRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.ListTokensResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.ListTokensResponse]]:
        """ListTokens method receives a ListTokensRequest message and returns a
        ListTokensResponse message.
        """
    @abc.abstractmethod
    def GetToken(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.GetTokenRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.GetTokenResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.GetTokenResponse]]:
        """GetToken method receives a GetTokenRequest message and returns a
        GetTokenResponse message.
        """
    @abc.abstractmethod
    def DeleteToken(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.DeleteTokenRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.DeleteTokenResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.DeleteTokenResponse]]:
        """DeleteToken method receives a DeleteTokenRequest message and returns
        a DeleteTokenResponse message.
        """
    @abc.abstractmethod
    def ValidateToken(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.ValidateTokenRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.ValidateTokenResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.ValidateTokenResponse]]:
        """ValidateToken method receives a ValidateTokenRequest message and returns
        a ValidateTokenResponse message.
        """
    @abc.abstractmethod
    def ListPipelineTriggerRecords(
        self,
        request: core.mgmt.v1beta.metric_pb2.ListPipelineTriggerRecordsRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.metric_pb2.ListPipelineTriggerRecordsResponse, collections.abc.Awaitable[core.mgmt.v1beta.metric_pb2.ListPipelineTriggerRecordsResponse]]:
        """========== Metric endpoints

        ListPipelineTriggerRecords method receives a
        ListPipelineTriggerRecordsRequest message and returns a
        ListPipelineTriggerRecordsResponse message.
        """
    @abc.abstractmethod
    def ListPipelineTriggerTableRecords(
        self,
        request: core.mgmt.v1beta.metric_pb2.ListPipelineTriggerTableRecordsRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.metric_pb2.ListPipelineTriggerTableRecordsResponse, collections.abc.Awaitable[core.mgmt.v1beta.metric_pb2.ListPipelineTriggerTableRecordsResponse]]:
        """ListPipelineTriggerTableRecords method receives a
        ListPipelineTriggerTableRecordsRequest message and returns a
        ListPipelineTriggerTableRecordsResponse message.
        """
    @abc.abstractmethod
    def ListPipelineTriggerChartRecords(
        self,
        request: core.mgmt.v1beta.metric_pb2.ListPipelineTriggerChartRecordsRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.metric_pb2.ListPipelineTriggerChartRecordsResponse, collections.abc.Awaitable[core.mgmt.v1beta.metric_pb2.ListPipelineTriggerChartRecordsResponse]]:
        """ListPipelineTriggerChartRecords method receives a
        ListPipelineTriggerChartRecordsRequest message and returns a
        ListPipelineTriggerChartRecordsResponse message.
        """
    @abc.abstractmethod
    def ListConnectorExecuteRecords(
        self,
        request: core.mgmt.v1beta.metric_pb2.ListConnectorExecuteRecordsRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.metric_pb2.ListConnectorExecuteRecordsResponse, collections.abc.Awaitable[core.mgmt.v1beta.metric_pb2.ListConnectorExecuteRecordsResponse]]:
        """ListConnectorExecuteRecords method receives a
        ListConnectorExecuteRecordsRequest message and returns a
        ListConnectorExecuteRecordsResponse message.
        """
    @abc.abstractmethod
    def ListConnectorExecuteTableRecords(
        self,
        request: core.mgmt.v1beta.metric_pb2.ListConnectorExecuteTableRecordsRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.metric_pb2.ListConnectorExecuteTableRecordsResponse, collections.abc.Awaitable[core.mgmt.v1beta.metric_pb2.ListConnectorExecuteTableRecordsResponse]]:
        """ListConnectorExecuteTableRecords method receives a
        ListConnectorExecuteTableRecordsRequest message and returns a
        ListConnectorExecuteTableRecordsResponse message.
        """
    @abc.abstractmethod
    def ListConnectorExecuteChartRecords(
        self,
        request: core.mgmt.v1beta.metric_pb2.ListConnectorExecuteChartRecordsRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.metric_pb2.ListConnectorExecuteChartRecordsResponse, collections.abc.Awaitable[core.mgmt.v1beta.metric_pb2.ListConnectorExecuteChartRecordsResponse]]:
        """ListConnectorExecuteChartRecords method receives a
        ListConnectorExecuteChartRecordsRequest message and returns a
        ListConnectorExecuteChartRecordsResponse message.
        """
    @abc.abstractmethod
    def AuthTokenIssuer(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.AuthTokenIssuerRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.AuthTokenIssuerResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.AuthTokenIssuerResponse]]:
        """AuthTokenIssuer endpoint"""
    @abc.abstractmethod
    def AuthLogin(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.AuthLoginRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.AuthLoginResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.AuthLoginResponse]]:
        """Auth Login endpoint"""
    @abc.abstractmethod
    def AuthLogout(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.AuthLogoutRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.AuthLogoutResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.AuthLogoutResponse]]:
        """Auth Logout endpoint"""
    @abc.abstractmethod
    def AuthChangePassword(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.AuthChangePasswordRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.AuthChangePasswordResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.AuthChangePasswordResponse]]:
        """Auth Change password endpoint"""
    @abc.abstractmethod
    def AuthValidateAccessToken(
        self,
        request: core.mgmt.v1beta.mgmt_pb2.AuthValidateAccessTokenRequest,
        context: _ServicerContext,
    ) -> typing.Union[core.mgmt.v1beta.mgmt_pb2.AuthValidateAccessTokenResponse, collections.abc.Awaitable[core.mgmt.v1beta.mgmt_pb2.AuthValidateAccessTokenResponse]]:
        """Auth AccessToken validation endpoint"""

def add_MgmtPublicServiceServicer_to_server(servicer: MgmtPublicServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
