# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vdp/model/v1alpha/task_keypoint.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import field_behavior_pb2 as google_dot_api_dot_field__behavior__pb2
from vdp.model.v1alpha import common_pb2 as vdp_dot_model_dot_v1alpha_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%vdp/model/v1alpha/task_keypoint.proto\x12\x11vdp.model.v1alpha\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1evdp/model/v1alpha/common.proto\"C\n\x08Keypoint\x12\x11\n\x01x\x18\x01 \x01(\x02\x42\x03\xe0\x41\x03R\x01x\x12\x11\n\x01y\x18\x02 \x01(\x02\x42\x03\xe0\x41\x03R\x01y\x12\x11\n\x01v\x18\x03 \x01(\x02\x42\x03\xe0\x41\x03R\x01v\"\xb3\x01\n\x0eKeypointObject\x12>\n\tkeypoints\x18\x01 \x03(\x0b\x32\x1b.vdp.model.v1alpha.KeypointB\x03\xe0\x41\x03R\tkeypoints\x12\x19\n\x05score\x18\x02 \x01(\x02\x42\x03\xe0\x41\x03R\x05score\x12\x46\n\x0c\x62ounding_box\x18\x03 \x01(\x0b\x32\x1e.vdp.model.v1alpha.BoundingBoxB\x03\xe0\x41\x03R\x0b\x62oundingBox\"[\n\rKeypointInput\x12\x1d\n\timage_url\x18\x01 \x01(\tH\x00R\x08imageUrl\x12#\n\x0cimage_base64\x18\x02 \x01(\tH\x00R\x0bimageBase64B\x06\n\x04type\"R\n\x0eKeypointOutput\x12@\n\x07objects\x18\x01 \x03(\x0b\x32!.vdp.model.v1alpha.KeypointObjectB\x03\xe0\x41\x03R\x07objectsB\xd2\x01\n\x15\x63om.vdp.model.v1alphaB\x11TaskKeypointProtoP\x01Z@github.com/instill-ai/protogen-go/vdp/model/v1alpha;modelv1alpha\xa2\x02\x03VMX\xaa\x02\x11Vdp.Model.V1alpha\xca\x02\x11Vdp\\Model\\V1alpha\xe2\x02\x1dVdp\\Model\\V1alpha\\GPBMetadata\xea\x02\x13Vdp::Model::V1alphab\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vdp.model.v1alpha.task_keypoint_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025com.vdp.model.v1alphaB\021TaskKeypointProtoP\001Z@github.com/instill-ai/protogen-go/vdp/model/v1alpha;modelv1alpha\242\002\003VMX\252\002\021Vdp.Model.V1alpha\312\002\021Vdp\\Model\\V1alpha\342\002\035Vdp\\Model\\V1alpha\\GPBMetadata\352\002\023Vdp::Model::V1alpha'
  _KEYPOINT.fields_by_name['x']._options = None
  _KEYPOINT.fields_by_name['x']._serialized_options = b'\340A\003'
  _KEYPOINT.fields_by_name['y']._options = None
  _KEYPOINT.fields_by_name['y']._serialized_options = b'\340A\003'
  _KEYPOINT.fields_by_name['v']._options = None
  _KEYPOINT.fields_by_name['v']._serialized_options = b'\340A\003'
  _KEYPOINTOBJECT.fields_by_name['keypoints']._options = None
  _KEYPOINTOBJECT.fields_by_name['keypoints']._serialized_options = b'\340A\003'
  _KEYPOINTOBJECT.fields_by_name['score']._options = None
  _KEYPOINTOBJECT.fields_by_name['score']._serialized_options = b'\340A\003'
  _KEYPOINTOBJECT.fields_by_name['bounding_box']._options = None
  _KEYPOINTOBJECT.fields_by_name['bounding_box']._serialized_options = b'\340A\003'
  _KEYPOINTOUTPUT.fields_by_name['objects']._options = None
  _KEYPOINTOUTPUT.fields_by_name['objects']._serialized_options = b'\340A\003'
  _KEYPOINT._serialized_start=125
  _KEYPOINT._serialized_end=192
  _KEYPOINTOBJECT._serialized_start=195
  _KEYPOINTOBJECT._serialized_end=374
  _KEYPOINTINPUT._serialized_start=376
  _KEYPOINTINPUT._serialized_end=467
  _KEYPOINTOUTPUT._serialized_start=469
  _KEYPOINTOUTPUT._serialized_end=551
# @@protoc_insertion_point(module_scope)
