"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import abc
import collections.abc
import grpc
import grpc.aio
import mgmt.v1beta.mgmt_pb2
import typing

_T = typing.TypeVar("_T")

class _MaybeAsyncIterator(collections.abc.AsyncIterator[_T], collections.abc.Iterator[_T], metaclass=abc.ABCMeta): ...

class _ServicerContext(grpc.ServicerContext, grpc.aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

class MgmtPrivateServiceStub:
    """Mgmt service responds to internal access"""

    def __init__(self, channel: typing.Union[grpc.Channel, grpc.aio.Channel]) -> None: ...
    ListUsersAdmin: grpc.UnaryUnaryMultiCallable[
        mgmt.v1beta.mgmt_pb2.ListUsersAdminRequest,
        mgmt.v1beta.mgmt_pb2.ListUsersAdminResponse,
    ]
    """ListUsersAdmin method receives a ListUsersAdminRequest message and returns
    a ListUsersAdminResponse message.
    """

    GetUserAdmin: grpc.UnaryUnaryMultiCallable[
        mgmt.v1beta.mgmt_pb2.GetUserAdminRequest,
        mgmt.v1beta.mgmt_pb2.GetUserAdminResponse,
    ]
    """GetUserAdmin method receives a GetUserAdminRequest message and returns
    a GetUserAdminResponse message.
    """

    LookUpUserAdmin: grpc.UnaryUnaryMultiCallable[
        mgmt.v1beta.mgmt_pb2.LookUpUserAdminRequest,
        mgmt.v1beta.mgmt_pb2.LookUpUserAdminResponse,
    ]
    """LookUpUserAdmin method receives a LookUpUserAdminRequest message and
    returns a LookUpUserAdminResponse
    """

    ListOrganizationsAdmin: grpc.UnaryUnaryMultiCallable[
        mgmt.v1beta.mgmt_pb2.ListOrganizationsAdminRequest,
        mgmt.v1beta.mgmt_pb2.ListOrganizationsAdminResponse,
    ]
    """ListOrganizationsAdmin method receives a ListOrganizationsAdminRequest message and returns
    a ListOrganizationsAdminResponse message.
    """

    GetOrganizationAdmin: grpc.UnaryUnaryMultiCallable[
        mgmt.v1beta.mgmt_pb2.GetOrganizationAdminRequest,
        mgmt.v1beta.mgmt_pb2.GetOrganizationAdminResponse,
    ]
    """GetOrganizationAdmin method receives a GetOrganizationAdminRequest message and returns
    a GetOrganizationAdminResponse message.
    """

    LookUpOrganizationAdmin: grpc.UnaryUnaryMultiCallable[
        mgmt.v1beta.mgmt_pb2.LookUpOrganizationAdminRequest,
        mgmt.v1beta.mgmt_pb2.LookUpOrganizationAdminResponse,
    ]
    """LookUpOrganizationAdmin method receives a LookUpOrganizationAdminRequest message and
    returns a LookUpOrganizationAdminResponse
    """

    CheckNamespaceAdmin: grpc.UnaryUnaryMultiCallable[
        mgmt.v1beta.mgmt_pb2.CheckNamespaceAdminRequest,
        mgmt.v1beta.mgmt_pb2.CheckNamespaceAdminResponse,
    ]
    """Check if a namespace is in use

    Returns the availability of a namespace or, alternatively, the type of
    resource that is using it.
    """

    CheckNamespaceByUIDAdmin: grpc.UnaryUnaryMultiCallable[
        mgmt.v1beta.mgmt_pb2.CheckNamespaceByUIDAdminRequest,
        mgmt.v1beta.mgmt_pb2.CheckNamespaceByUIDAdminResponse,
    ]
    """Check if a namespace is in use by UID

    Returns the availability of a namespace or, alternatively, the type of
    resource that is using it.
    """

class MgmtPrivateServiceAsyncStub:
    """Mgmt service responds to internal access"""

    ListUsersAdmin: grpc.aio.UnaryUnaryMultiCallable[
        mgmt.v1beta.mgmt_pb2.ListUsersAdminRequest,
        mgmt.v1beta.mgmt_pb2.ListUsersAdminResponse,
    ]
    """ListUsersAdmin method receives a ListUsersAdminRequest message and returns
    a ListUsersAdminResponse message.
    """

    GetUserAdmin: grpc.aio.UnaryUnaryMultiCallable[
        mgmt.v1beta.mgmt_pb2.GetUserAdminRequest,
        mgmt.v1beta.mgmt_pb2.GetUserAdminResponse,
    ]
    """GetUserAdmin method receives a GetUserAdminRequest message and returns
    a GetUserAdminResponse message.
    """

    LookUpUserAdmin: grpc.aio.UnaryUnaryMultiCallable[
        mgmt.v1beta.mgmt_pb2.LookUpUserAdminRequest,
        mgmt.v1beta.mgmt_pb2.LookUpUserAdminResponse,
    ]
    """LookUpUserAdmin method receives a LookUpUserAdminRequest message and
    returns a LookUpUserAdminResponse
    """

    ListOrganizationsAdmin: grpc.aio.UnaryUnaryMultiCallable[
        mgmt.v1beta.mgmt_pb2.ListOrganizationsAdminRequest,
        mgmt.v1beta.mgmt_pb2.ListOrganizationsAdminResponse,
    ]
    """ListOrganizationsAdmin method receives a ListOrganizationsAdminRequest message and returns
    a ListOrganizationsAdminResponse message.
    """

    GetOrganizationAdmin: grpc.aio.UnaryUnaryMultiCallable[
        mgmt.v1beta.mgmt_pb2.GetOrganizationAdminRequest,
        mgmt.v1beta.mgmt_pb2.GetOrganizationAdminResponse,
    ]
    """GetOrganizationAdmin method receives a GetOrganizationAdminRequest message and returns
    a GetOrganizationAdminResponse message.
    """

    LookUpOrganizationAdmin: grpc.aio.UnaryUnaryMultiCallable[
        mgmt.v1beta.mgmt_pb2.LookUpOrganizationAdminRequest,
        mgmt.v1beta.mgmt_pb2.LookUpOrganizationAdminResponse,
    ]
    """LookUpOrganizationAdmin method receives a LookUpOrganizationAdminRequest message and
    returns a LookUpOrganizationAdminResponse
    """

    CheckNamespaceAdmin: grpc.aio.UnaryUnaryMultiCallable[
        mgmt.v1beta.mgmt_pb2.CheckNamespaceAdminRequest,
        mgmt.v1beta.mgmt_pb2.CheckNamespaceAdminResponse,
    ]
    """Check if a namespace is in use

    Returns the availability of a namespace or, alternatively, the type of
    resource that is using it.
    """

    CheckNamespaceByUIDAdmin: grpc.aio.UnaryUnaryMultiCallable[
        mgmt.v1beta.mgmt_pb2.CheckNamespaceByUIDAdminRequest,
        mgmt.v1beta.mgmt_pb2.CheckNamespaceByUIDAdminResponse,
    ]
    """Check if a namespace is in use by UID

    Returns the availability of a namespace or, alternatively, the type of
    resource that is using it.
    """

class MgmtPrivateServiceServicer(metaclass=abc.ABCMeta):
    """Mgmt service responds to internal access"""

    @abc.abstractmethod
    def ListUsersAdmin(
        self,
        request: mgmt.v1beta.mgmt_pb2.ListUsersAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[mgmt.v1beta.mgmt_pb2.ListUsersAdminResponse, collections.abc.Awaitable[mgmt.v1beta.mgmt_pb2.ListUsersAdminResponse]]:
        """ListUsersAdmin method receives a ListUsersAdminRequest message and returns
        a ListUsersAdminResponse message.
        """

    @abc.abstractmethod
    def GetUserAdmin(
        self,
        request: mgmt.v1beta.mgmt_pb2.GetUserAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[mgmt.v1beta.mgmt_pb2.GetUserAdminResponse, collections.abc.Awaitable[mgmt.v1beta.mgmt_pb2.GetUserAdminResponse]]:
        """GetUserAdmin method receives a GetUserAdminRequest message and returns
        a GetUserAdminResponse message.
        """

    @abc.abstractmethod
    def LookUpUserAdmin(
        self,
        request: mgmt.v1beta.mgmt_pb2.LookUpUserAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[mgmt.v1beta.mgmt_pb2.LookUpUserAdminResponse, collections.abc.Awaitable[mgmt.v1beta.mgmt_pb2.LookUpUserAdminResponse]]:
        """LookUpUserAdmin method receives a LookUpUserAdminRequest message and
        returns a LookUpUserAdminResponse
        """

    @abc.abstractmethod
    def ListOrganizationsAdmin(
        self,
        request: mgmt.v1beta.mgmt_pb2.ListOrganizationsAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[mgmt.v1beta.mgmt_pb2.ListOrganizationsAdminResponse, collections.abc.Awaitable[mgmt.v1beta.mgmt_pb2.ListOrganizationsAdminResponse]]:
        """ListOrganizationsAdmin method receives a ListOrganizationsAdminRequest message and returns
        a ListOrganizationsAdminResponse message.
        """

    @abc.abstractmethod
    def GetOrganizationAdmin(
        self,
        request: mgmt.v1beta.mgmt_pb2.GetOrganizationAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[mgmt.v1beta.mgmt_pb2.GetOrganizationAdminResponse, collections.abc.Awaitable[mgmt.v1beta.mgmt_pb2.GetOrganizationAdminResponse]]:
        """GetOrganizationAdmin method receives a GetOrganizationAdminRequest message and returns
        a GetOrganizationAdminResponse message.
        """

    @abc.abstractmethod
    def LookUpOrganizationAdmin(
        self,
        request: mgmt.v1beta.mgmt_pb2.LookUpOrganizationAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[mgmt.v1beta.mgmt_pb2.LookUpOrganizationAdminResponse, collections.abc.Awaitable[mgmt.v1beta.mgmt_pb2.LookUpOrganizationAdminResponse]]:
        """LookUpOrganizationAdmin method receives a LookUpOrganizationAdminRequest message and
        returns a LookUpOrganizationAdminResponse
        """

    @abc.abstractmethod
    def CheckNamespaceAdmin(
        self,
        request: mgmt.v1beta.mgmt_pb2.CheckNamespaceAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[mgmt.v1beta.mgmt_pb2.CheckNamespaceAdminResponse, collections.abc.Awaitable[mgmt.v1beta.mgmt_pb2.CheckNamespaceAdminResponse]]:
        """Check if a namespace is in use

        Returns the availability of a namespace or, alternatively, the type of
        resource that is using it.
        """

    @abc.abstractmethod
    def CheckNamespaceByUIDAdmin(
        self,
        request: mgmt.v1beta.mgmt_pb2.CheckNamespaceByUIDAdminRequest,
        context: _ServicerContext,
    ) -> typing.Union[mgmt.v1beta.mgmt_pb2.CheckNamespaceByUIDAdminResponse, collections.abc.Awaitable[mgmt.v1beta.mgmt_pb2.CheckNamespaceByUIDAdminResponse]]:
        """Check if a namespace is in use by UID

        Returns the availability of a namespace or, alternatively, the type of
        resource that is using it.
        """

def add_MgmtPrivateServiceServicer_to_server(servicer: MgmtPrivateServiceServicer, server: typing.Union[grpc.Server, grpc.aio.Server]) -> None: ...
